name: grocery_mule
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  flutter_spinkit: ^5.1.0
  google_sign_in: ^5.3.1
  uuid: ^3.0.6
  number_inc_dec: ^0.8.0
  badges: ^2.0.2
  provider: ^6.0.2
  fluttertoast: ^8.0.9
  multi_select_flutter: ^4.1.2
  introduction_screen: ^3.0.2
  dots_indicator: ^2.1.0
  shared_preferences: ^2.0.15
  after_layout: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
